[profile.default]
solc_version = "0.8.20"
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 20000
libs = ["lib"]
test = 'test/foundry'
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./out"}]
evm_version = "shanghai"

[fmt]
tab_width = 2

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 2000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
  'forge-std=lib/forge-std/src',
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'contracts/=src/contracts/'
]



